### ISSUE TITLE
Single Dockerfile

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#395]
Currently we use 3 docker files; _base_, _web_ and _worker_.

The only thing that happens in _web_ and _worker_ is that the ENTRYPOINT and the COMMAND are altered between Gunicon and Celery.

We can achieve this all from a single image which defaults to run Gunicorn. When the worker starts this can have those settings changed within the orchestrator.

In docker-compose this would look something like:

```yaml
worker:
  image: pjuu/pjuu:latest
  entrypoint: celery
  command: ["-A", "pjuu.celery_app", "worker"]
  deploy:
    restart_policy:
      condition: any
  links:
    - redis
    - mongo
  container_name: worker
  depends_on:
    - redis
    - mongo
```

You can also alter these arguments in Kubernetes:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
```

https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes
